##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  manager:
    label: 'Manager'
    htmlClass: 'sidebar-manager'
    sortOrder: 9999
    groups:
      default:
        actions:
          installedPlugins:
            label: "Installed Bundles"
            action: 'manager_bundle_index'
            sortOrder: 1
          storeBundles:
            label: 'Browse Bundles in Store »'
            action: 'manager_bundle_browse'
            sortOrder: 2
          storeThemes:
            label: 'Browse Themes in Store »'
            action: ''
            sortOrder: 3