##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  content:
    groups:
      posts:
        label: 'Posts'
        sortOrder: 1
        actions:
          help:
            label: "Posts"
            action: 'post_index_index'
            sortOrder: 1