# /*
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
system_config:
  tab:
    id: 'core_post'
    label: 'Post'
  sections:
    post:
      label: 'Post'
      tab: 'core_post'
      scope: 'default|website|website_view'
      groups:
        country_optionsc:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_countryc:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
    comments:
      label: 'Comments'
      tab: 'core_post'
      scope: 'default|website|website_view'
      groups:
        country_optionsd:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_countryd:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'