##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  programcms:
    label: 'Welcome'
    htmlClass: 'sidebar-logo'
    sortOrder: 1
    groups:
      default:
        actions:
          help:
            label: "Help"
            action: 'catalog_category_index'
            sortOrder: 1
          about:
            label: 'About'
            action: ''
            sortOrder: 2
          gettingstarted:
            label: 'Getting Started'
            action: ''
            sortOrder: 3
          updates:
            label: 'Check for Updates'
            action: ''
            sortOrder: 4
      upgrade:
        label: 'Upgrade'
        actions:
          extensions:
            label: 'Get Extensions & Themes »'
            action: ''
          programcmsplus:
            label: 'Upgrade to ProgramCMS Plus »'
            action: ''
  dashboard:
    label: 'Dashboard'
    htmlClass: 'sidebar-dashboard'
    action: 'admin_dashboard_index'
    sortOrder: 2
  system:
    label: 'System'
    htmlClass: 'sidebar-system'
    sortOrder: 9
    groups:
      tools:
        label: 'Tools'
        actions:
          cache:
            label: 'Cache Management'
            action: 'admin_tool_cache'
      dataTransfer:
        label: 'Data Transfer'
        actions:
          import:
            label: 'Import'
            action: ''
          export:
            label: 'Export'
            action: ''
          history:
            label: 'History'
            action: ''
      roles:
        label: 'Permissions'
        actions:
          roles:
            label: 'Roles'
            action: 'acl_role_index'
          adminUsers:
            label: 'Admin Users'
            action: 'admin_user_index'