##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_advanced'
    label: 'Advanced'
    sortOrder: 99999
  sections:
    system:
      label: 'System'
      tab: 'core_advanced'
      scope: 'default'
      groups:
        backend_theme:
          label: 'Backend Theme'
          scope: 'default'
          fields:
            applied_theme:
              label: 'Applied Theme'
              type: 'select'
              source: ProgramCms\AdminBundle\Model\Provider\DataSource\ThemeSelector
              helpMessage: 'If no value is specified, the system default is used. The system default may be modified by third-party bundles.'
              scope: 'default'
    developer:
      label: 'Developer'
      tab: 'core_advanced'
      scope: 'default'
      groups:
        developer_mode:
          label: 'Developer Mode'
          scope: 'default'
          fields:
            activate:
              type: 'switcher'
              label: 'Activate Developer Mode'
              defaultValue: 1
              scope: 'default'
        template_settings:
          label: 'Template Settings'
          scope: 'default'
          fields:
            minify_twig:
              type: 'switcher'
              label: 'Minify Twig'
              scope: 'default|can_restore'
