##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\CaptchaBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'