##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
acl:
  ProgramCmsUserBundle_user:
    label: 'Core Permissions'
    ProgramCmsUserBundle_user_edit:
      label: 'Edit Account'
      ProgramCmsUserBundle_user_edit_my:
        label: 'My Account'
        ProgramCmsUserBundle_user_edit_email:
          label: 'Edit Email Address'
        ProgramCmsUserBundle_user_edit_name:
          label: 'Edit Full Name'
        ProgramCmsUserBundle_user_edit_username:
          label: 'Edit Username'
        ProgramCmsUserBundle_user_edit_password:
          label: 'Change Password'
      ProgramCmsUserBundle_user_edit_all:
        label: 'Edit All Users'
    ProgramCmsUserBundle_user_lock:
      label: 'Lock All Users'