##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
template:
  recovery_email:
    area: 'frontend'
    label: 'Recovery Email'
    file: 'recovery.html.twig'