##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\UserBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\UserBundle\Security\PermissionVoter:
    tags: [security.voter]

#  ProgramCms\UserBundle\Model\Provider\Listing\DataProvider:
#    arguments:
#      $filterStrategies:
#        websiteView: '@ProgramCms\UserBundle\Ui\DataProvider\WebsiteViewFilter'