##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  website:
    label: 'Websites'
    htmlClass: 'sidebar-website'
    sortOrder: 8
    groups:
      settings:
        label: 'Settings'
        actions:
          websites:
            label: 'All Web Sites'
            action: ''
          config:
            label: 'Configuration'
            action: ''
          terms:
            label: 'Terms and Conditions'
            action: ''
      attributes:
        label: 'Attributes'
        actions:
          category:
            label: 'Category'
            action: ''
          post:
            label: 'Post'
            action: ''
          user:
            label: 'User'
            action: ''