##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  website:
    label: 'Websites'
    htmlClass: 'sidebar-website'
    sortOrder: 8
    groups:
      settings:
        label: 'Settings'
        sortOrder: 1
        actions:
          websites:
            label: 'All Web Sites'
            action: 'website_website_index'
          config:
            label: 'Configuration'
            action: 'config_systemconfig_index'
          terms:
            label: 'Terms and Conditions'
            action: ''