##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_general'
    label: 'General'
    sortOrder: 0
  sections:
    general:
      label: 'General'
      tab: 'core_general'
      scope: 'default|website|website_view'
      groups:
        country_options:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view|can_restore'
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view|can_restore'
        locale_options:
          label: 'Locale Options'
          scope: 'default|website|website_view'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
              scope: 'default|website|website_view|can_restore'
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\LocaleSelector
              scope: 'default|website|website_view|can_restore'
        website_information:
          label: 'Website Information'
          scope: 'default|website|website_view'
          fields:
            website_name:
              label: 'Website Name'
              type: 'text'
              scope: 'default|website|website_view'
            website_phone:
              label: 'Website Phone Number'
              type: 'text'
              scope: 'default|website|website_view'
            region:
              label: 'Region/State'
              type: 'text'
              scope: 'default|website|website_view'
            zip_code:
              label: 'ZIP/Postal Code'
              type: 'text'
              scope: 'default|website|website_view'
            city:
              label: 'City'
              type: 'text'
              scope: 'default|website|website_view'
            address:
              label: 'Street Address'
              type: 'text'
              scope: 'default|website|website_view'
            address_line2:
              label: 'Street Address Line 2'
              type: 'text'
              scope: 'default|website|website_view'
            country:
              label: 'Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
    web:
      label: 'Web'
      tab: 'core_general'
      scope: 'default|website|website_view'
      groups:
        urls:
          label: 'Base URLs'
          scope: 'default|website|website_view'
          fields:
            base_url:
              label: 'Base URL'
              type: 'text'
              scope: 'default|website|website_view|can_restore'
        default_pages:
          label: 'Default Pages'
          scope: 'default|website|website_view'
          fields:
            cms:
              label: 'CMS Home Page'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\LocaleSelector
              scope: 'default|website|website_view|can_restore'
    theme_config:
      label: 'Theme Configuration'
      tab: 'core_general'
      scope: 'default|website|website_view'
      groups:
        theme_configuration:
          label: 'Theme Configuration'
          scope: 'default|website|website_view'
          fields:
            applied_theme:
              label: 'Applied Theme'
              type: 'select'
              source: ProgramCms\ThemeBundle\Model\Provider\DataSource\ThemeSelector
              helpMessage: 'If no value is specified, the system default is used. The system default may be modified by third-party bundles.'
              scope: 'default|website|website_view|can_restore'