##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_general'
    label: 'General'
    sortOrder: 0
  sections:
    general:
      label: 'General'
      tab: 'core_general'
      groups:
        country_options:
          label: 'Country Options'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
        local_options:
          label: 'Locale Options'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\LocaleSelector
    web:
      label: 'Web'
      tab: 'core_general'
      groups:
        country_options:
          label: 'Country Options'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
    theme_config:
      label: 'Theme Configuration'
      tab: 'core_general'
      groups:
        country_options:
          label: 'Theme Configuration'
          fields:
            applied_theme:
              label: 'Applied Theme'
              type: 'select'
              source: ProgramCms\ThemeBundle\Model\Provider\DataSource\ThemeSelector
              helpMessage: 'If no value is specified, the system default is used. The system default may be modified by third-party bundles.'