##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_general'
    label: 'General'
  sections:
    general:
      label: 'General'
      tab: 'core_general'
      groups:
        country_options:
          label: 'Country Options'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
        local_options:
          label: 'Locale Options'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
    web:
      label: 'Web'
      tab: 'core_general'
      groups:
        country_options:
          label: 'Country Options'
          fields:
            default_country:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
            allowed_countries:
              label: 'Allow Countries'
              type: 'multiselect'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
        local_options:
          label: 'Locale Options'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
