##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  users:
    label: 'Users'
    htmlClass: 'sidebar-users'
    sortOrder: 3
    groups:
      default:
        actions:
          all:
            label: "All Users"
            action: 'user_index_index'
            sortOrder: 1
          online:
            label: 'Now Online'
            action: 'user_index_connected'
            sortOrder: 2
          groups:
            label: 'User Groups'
            action: 'user_group_index'
            sortOrder: 3