##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  users:
    label: 'Users'
    htmlClass: 'sidebar-users'
    sortOrder: 3
    acl: 'ProgramCmsUserBundle_user'
    groups:
      default:
        actions:
          all:
            label: "All Users"
            action: 'user_index_index'
            sortOrder: 1
            acl: 'ProgramCmsUserBundle_user_view'
          online:
            label: 'Now Online'
            action: 'user_index_connected'
            sortOrder: 2
          groups:
            label: 'User Groups'
            action: 'user_group_index'
            sortOrder: 3
          login_attempts:
            label: 'Login Attempts'
            action: 'user_group_index'
            sortOrder: 4
          locked_users:
            label: 'Locked Users'
            action: 'user_group_index'
            sortOrder: 4