# /*
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
menu:
  menu1:
    label: 'Dashboard'
    icon: ''
    items:
      clients:
        label: 'All Clients'
        path: ''