services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.


  ProgramCms\CoreBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\CoreBundle\Model\Utils\BundleManager:
    arguments:
      $container: '@service_container'