##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\CoreBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'
      - '../../View/Design/Fallback/Rule/'
      - '../../Theme/'

  ProgramCms\CoreBundle\Model\Utils\BundleManager:
    arguments:
      $container: '@service_container'

  ProgramCms\CoreBundle\Model\ObjectManagerInterface:
    class: ProgramCms\CoreBundle\Model\ObjectManager

  ProgramCms\CoreBundle\Config\FileResolverInterface:
    class: ProgramCms\CoreBundle\App\Config\FileResolver

  ProgramCms\CoreBundle\View\Design\FileResolution\Fallback\ResolverInterface:
    class: ProgramCms\CoreBundle\View\Design\FileResolution\Fallback\Resolver\Simple

  ProgramCms\CoreBundle\View\Template\MinifierInterface:
    class: ProgramCms\CoreBundle\View\Template\Twig\Minifier

  ProgramCms\CoreBundle\App\RequestInterface:
    class: ProgramCms\CoreBundle\App\Request\Request

  ProgramCms\CoreBundle\App\AreaInterface:
    class: ProgramCms\CoreBundle\App\Area

  ProgramCms\CoreBundle\Model\Db\Entity\EntityInterface:
    class: ProgramCms\CoreBundle\Model\Db\Entity\AbstractEntity

  ProgramCms\CoreBundle\DateTime\TransformerInterface:
    class: ProgramCms\CoreBundle\DateTime\Transformer