##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_category'
    label: 'Catalog'
  sections:
    category:
      label: 'Category'
      tab: 'core_category'
      scope: 'default|website|website_view'
      groups:
        country_optionsb:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_countryb:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
        local_options:
          label: 'Locale Options'
          scope: 'default|website|website_view'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
              scope: 'default|website|website_view'
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
              scope: 'default|website|website_view'