##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  marketing:
    groups:
      communication:
        actions:
          newsletters:
            label: "Newsletters"
            action: 'newsletter_index_index'
            sortOrder: 1
          newsletterSubscribers:
            label: "Newsletter Subscribers"
            action: ''
            sortOrder: 2