##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  sections:
    newsletter:
      label: 'Newsletter'
      tab: 'user'
      scope: 'default|website|website_view'
      groups:
        general:
          label: 'General'
          scope: 'default|website|website_view'
          fields:
            enable:
              type: 'switcher'
              label: 'Enable Newsletter'
              scope: 'default|website|website_view'