##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  marketing:
    label: 'Marketing'
    htmlClass: 'sidebar-marketing'
    sortOrder: 6
    groups:
      communication:
        label: 'Communication'
        actions:
          emailTemplates:
            label: "Email Templates"
            action: ''
            sortOrder: 1
      seoSearch:
        label: 'SEO & Search'
        actions:
          urlRewrites:
            label: "URL Rewrites"
            action: ''
            sortOrder: 1
          searchTerms:
            label: "Search Terms"
            action: ''
            sortOrder: 1
      earn:
        label: 'Earn & Monetization'
        actions:
          urlRewrites:
            label: "Google Adsense"
            action: ''
            sortOrder: 1