# /*
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
router:
  frontend:
    favorite_root:
      frontName: 'favorite'
  adminhtml:
    favorite_root:
      frontName: 'favorite'