##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
config:
  default:
    system:
      backend_theme:
        applied_theme: 1
    developer:
      template_settings:
        minify_twig: 'on'
  website:
    admin:
      web:
        default:
          no_route: 'admin/noroute/index'
  website_view:
    admin:
      design:
        theme: 'programcms/backend'