##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
config:
  default:
    system:
      backend_theme:
        applied_theme: 'programcms/backend'
