##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  ProgramCms\AdminBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\CoreBundle\App\AreaList:
    arguments:
      - { adminhtml: { frontName: 'adminhtml', router: 'adminhtml' } }