##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  content:
    label: 'Content'
    htmlClass: 'sidebar-content'
    sortOrder: 5
    groups:
      elements:
        label: 'Elements'
        sortOrder: 1
        actions:
          help:
            label: "Pages"
            action: ''
            sortOrder: 1
          about:
            label: 'Piece of Content'
            action: ''
            sortOrder: 2