# /*
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
router:
  frontend:
    newsletter_root:
      frontName: 'newsletter'
  adminhtml:
    newsletter_root:
      frontName: 'newsletter'