##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_security'
    label: 'Security'
  sections:
    securitytxt:
      label: 'Security.txt'
      tab: 'core_security'
      scope: 'default|website|website_view'
      groups:
        country_optionse:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_countrye:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
        local_options:
          label: 'Locale Options'
          scope: 'default|website|website_view'
          fields:
            timezone:
              label: 'Timezone'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
              scope: 'default|website|website_view'
            locale:
              label: 'Locale'
              type: 'select'
              source: ProgramCms\UiBundle\Model\Provider\DataSource\TimeZoneSelector
              scope: 'default|website|website_view'
    google_recaptcha:
      label: 'Google reCAPTCHA'
      tab: 'core_security'
      scope: 'default|website|website_view'
      groups:
        country_optionsf:
          label: 'Country Options'
          scope: 'default|website|website_view'
          fields:
            default_countryf:
              label: 'Default Country'
              type: 'select'
              source: ProgramCms\WebsiteBundle\Model\Provider\CountrySelector
              scope: 'default|website|website_view'
