##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
router:
  frontend:
    user_root:
      frontName: 'config'
  adminhtml:
    user_root:
      frontName: 'config'