##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\ConfigBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\ConfigBundle\Model\ConfigSerializer:
    arguments:
      $container: '@service_container'

  ProgramCms\ConfigBundle\Model\Structure\AbstractElement:
    abstract: true
