##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    public: true # used to help instantiating block classes from container

  ProgramCms\ThemeBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Loader/'
      - '../../Node/'
      - '../../Parser/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\ThemeBundle\Loader\LayoutLoader:
    tags:
      - { name: 'twig.loader', priority: -1 } # Used to be able to continue to twig default loader