##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\ThemeBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Loader/'
      - '../../Node/'
      - '../../Parser/'
      - '../../Resources/'
      - '../../Tests/'
      - '../../Webpack/Generator'

  ProgramCms\ThemeBundle\Loader\LayoutLoader:
    tags:
      - { name: 'twig.loader', priority: -1 } # Used to be able to continue to twig default loader*

  ProgramCms\ThemeBundle\Extension\ThemeExtension:
    tags:
      - { name: 'twig.extension' }

  ProgramCms\CoreBundle\View\DesignInterface:
    class: ProgramCms\ThemeBundle\Model\View\Design

  ProgramCms\CoreBundle\View\Design\Theme\ThemeProviderInterface:
    class: ProgramCms\ThemeBundle\Model\Provider\ThemeProvider

  ProgramCms\ThemeBundle\Model\View\Design:
    arguments:
      $themes:
        frontend: 'ProgramCms/Blank'
        backend: 'Programcms/Backend'