##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\ThemeBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Loader/'
      - '../../Node/'
      - '../../Parser/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\ThemeBundle\Loader\LayoutLoader:
    tags:
      - { name: 'twig.loader', priority: -1 } # Used to be able to continue to twig default loader*

  ProgramCms\ThemeBundle\Extension\ThemeExtension:
    tags:
      - { name: 'twig.extension' }