# /*
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
# */
router:
  adminhtml:
    import_root:
      frontName: 'import'