##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
acl:
  ProgramCmsAdminBundle_admin:
    ProgramCmsPostBundle_post:
      ProgramCmsCommentBundle_comment:
        label: 'Post Comment Permissions'
        ProgramCmsCommentBundle_comment_edit:
          label: 'Edit Comments'
        ProgramCmsCommentBundle_comment_delete:
          label: 'Delete Comments'