##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
menu:
  drive:
    label: 'P-Drive'
    htmlClass: 'sidebar-drive'
    sortOrder: 10
    groups:
      default:
        actions:
          help:
            label: "All Files"
            action: 'drive_index_index'
            sortOrder: 1