##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
system_config:
  tab:
    id: 'core_advanced'
    label: 'Advanced'
    sortOrder: 99999
  sections:
    system:
      label: 'System'
      tab: 'core_advanced'
    developer:
      label: 'Developer'
      tab: 'core_advanced'
