##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\UiBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../App/Node/'
      - '../../App/Parser/'
      - '../../Tests/'

  ProgramCms\UiBundle\View\Element\UiComponentInterface:
    class: ProgramCms\UiBundle\Component\Wrapper\UiComponent

  # alias WebSiteSwitcher block
  ui.block.toolbar.website_switcher:
    class: ProgramCms\UiBundle\Block\Toolbar\WebsiteSwitcher
  # alias Fieldset
  ui.block.form.fieldset:
    class: ProgramCms\UiBundle\Component\Form\Fieldset
  ui.block.form.field:
    class: ProgramCms\UiBundle\Component\Form\Field
  # alias Form
  ui.block.form:
    class: ProgramCms\UiBundle\Component\Form\Form
  # alias Grid
  ui.block.listing:
    class: ProgramCms\UiBundle\Component\Listing\Listing
  ui.block.columns:
    class: ProgramCms\UiBundle\Component\Listing\Columns
  ui.block.column:
    class: ProgramCms\UiBundle\Component\Listing\Column
  ui.block.actionsColumn:
    class: ProgramCms\UiBundle\Component\Listing\ActionsColumn
  ui.block.selectionsColumn:
    class: ProgramCms\UiBundle\Component\Listing\SelectionsColumn
  ui.block.listing.search:
    class: ProgramCms\UiBundle\Component\Listing\Toolbar\Search
  ui.block.listing.toolbar:
    class: ProgramCms\UiBundle\Component\Listing\Toolbar
  ui.block.listing.filters:
    class: ProgramCms\UiBundle\Component\Listing\Toolbar\Filters
  ui.block.listing.massActions:
    class: ProgramCms\UiBundle\Component\Listing\Toolbar\MassActions
  ui.block.listing.pagination:
    class: ProgramCms\UiBundle\Component\Listing\Toolbar\Pagination
  ui.block.modal:
    class: ProgramCms\UiBundle\Component\Modal\Modal
  ui.block.form.button:
    class: ProgramCms\UiBundle\Component\Form\Element\Button