##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\UiBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  # alias WebSiteSwitcher block
  ui.block.toolbar.website_switcher:
    class: ProgramCms\UiBundle\Block\Toolbar\WebsiteSwitcher
  # alias Collapser
  ui.block.collapser:
    class: ProgramCms\UiBundle\Block\Collapser\Collapser
  # alias Fieldset
  ui.block.form.fieldset:
    class: ProgramCms\UiBundle\Component\Form\Fieldset
  ui.block.form.field:
    class: ProgramCms\UiBundle\Component\Form\Field
  ui.block.form.text:
    class: ProgramCms\UiBundle\Component\Form\Element\Text
  # alias Form
  ui.block.form:
    class: ProgramCms\UiBundle\Component\Form\Form
  ui.block.datasource:
    class: ProgramCms\UiBundle\Component\DataSource
  # alias Grid
  ui.block.grid:
    class: ProgramCms\UiBundle\Block\Grid\Grid