##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\UiBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  # alias WebSiteSwitcher block
  ui.block.toolbar.website_switcher:
    class: ProgramCms\UiBundle\Block\Toolbar\WebsiteSwitcher
  # alias Collapser block
  ui.block.collapser:
    class: ProgramCms\UiBundle\Block\Collapser\Collapser
  # alias Fieldset block
  ui.block.form.fieldset:
    class: ProgramCms\UiBundle\Block\Form\Fieldset
  # alias Form block
  ui.block.form:
    class: ProgramCms\UiBundle\Block\Form\Form