referenceContainers:
  head:
    blocks:
      gtm.script:
        class: ProgramCms\GtmBundle\Block\Gtm
        template: "@ProgramCmsGtmBundle/gtm.html.twig"
        before: "-"
  before.body:
    blocks:
      gtm.before.body.script:
        class: ProgramCms\GtmBundle\Block\Gtm
        template: "@ProgramCmsGtmBundle/before_body_gtm.html.twig"
        before: "-"
