##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
config:
  default:
    general:
      country_options:
        default_country: 'MA'
        allowed_countries: 'MA,US,FR'
      locale_options:
        timezone: 'Africa/Casablanca'
        locale: 'en_US'
    web:
      urls:
        base_url: '/'
    theme_config:
      theme_configuration:
        applied_theme: 'programcms/blank'