##
#  Copyright © ProgramCMS. All rights reserved.
#  See COPYING.txt for license details.
#
#  Developed by Mohamed EL QUCHIRI <elquchiri@gmail.com>
##
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  ProgramCms\WebsiteBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Resources/'
      - '../../Tests/'

  ProgramCms\CoreBundle\App\ScopeResolverPool:
    arguments:
      $scopeResolvers:
        default: '@ProgramCms\CoreBundle\App\ScopeResolver'
        website: '@ProgramCms\WebsiteBundle\Model\Resolver\Website'
        website_group: '@ProgramCms\WebsiteBundle\Model\Resolver\WebsiteGroup'
        website_view: '@ProgramCms\WebsiteBundle\Model\Resolver\WebsiteView'